### ISSUE TITLE
Signature Verify Fail

### ISSUE THREAD

**Issue by erwinpaulguevarra** [alipay/global-open-sdk-php#3]
Fatal error: Uncaught Exception: Response signature verify fail. in C:\laragon\www\alipay-sdk\BaseAlipayClient.php:64 Stack trace: #0 C:\laragon\www\alipay-sdk\example\UserPresentedCodePaymentTest.php(62): BaseAlipayClient->execute(Object(UserPresentedCodePaymentRequest)) #1 {main} thrown in C:\laragon\www\alipay-sdk\BaseAlipayClient.php on line 64

$result    = $alipayRsp->result; 
//return this message
{#19 ▼
  +"resultCode": "SUCCESS"
  +"resultMessage": "success."
  +"resultStatus": "S"
}

$verifyResult = openssl_verify($rspContent, $originalRspSignValue, $pubKey, OPENSSL_ALGO_SHA256);
//always return 0

**Comment by ant-songlin** [comment]
> Fatal error: Uncaught Exception: Response signature verify fail. in C:\laragon\www\alipay-sdk\BaseAlipayClient.php:64 Stack trace: #0 C:\laragon\www\alipay-sdk\example\UserPresentedCodePaymentTest.php(62): BaseAlipayClient->execute(Object(UserPresentedCodePaymentRequest)) #1 {main} thrown in C:\laragon\www\alipay-sdk\BaseAlipayClient.php on line 64
> 
> $result = $alipayRsp->result;
> //return this message
> {#19 ▼
> +"resultCode": "SUCCESS"
> +"resultMessage": "success."
> +"resultStatus": "S"
> }
> 
> $verifyResult = openssl_verify($rspContent, $originalRspSignValue, $pubKey, OPENSSL_ALGO_SHA256);
> //always return 0

-----------------------------------------------------------
Could you tell me which shop you are? Is $pubKey correct?

**Comment by patsiee** [comment]
I'm using SANDBOX client_id, everything is working except for the $this->checkRspSign($httpMethod, $path, $clientId, $rspTime, $rspBody, $rspSignValue);.
And also after using it for 3- 5 times I always receiving this error message "{"result":{"resultCode":"UNKNOWN_EXCEPTION","resultMessage":"unknown exception","resultStatus":"U"}}".

**Comment by jf-xufangjie** [comment]
hello，patsiee.could you make sure your alipayPublicKey is correct？This publicKey is provided by Ant Group.Not created by tool.

**Comment by jf-xufangjie** [comment]
By the way.Could you tell me which shop you are?

**Comment by yng666** [comment]
> hello，patsiee.could you make sure your alipayPublicKey is correct？This publicKey is provided by Ant Group.Not created by tool.
May I ask where can I check this alipayPublicKey? The trouble to provide a specific address, I can't see me here at (https://globalprod.alipay.com/order/myOrder.htm), anyway, I use a sand box, but use is the official offer tools to generate the secret key and public key, Where is this alipayPublicKey you're talking about?
